package com.ziania.accountmanager.domain;

public class TAccountmangerUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_user
     *
     * @mbg.generated Mon Apr 29 20:19:51 CST 2019
     */
    public static final String PK_ACCOUNT_USER_ID = "accountUserId";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_user
     *
     * @mbg.generated Mon Apr 29 20:19:51 CST 2019
     */
    public static final String ACCOUNT_USER_ID = "accountUserId";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_user
     *
     * @mbg.generated Mon Apr 29 20:19:51 CST 2019
     */
    public static final String ACCOUNT_USER_NAME = "accountUserName";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_user
     *
     * @mbg.generated Mon Apr 29 20:19:51 CST 2019
     */
    public static final String ACCOUNT_USER_AGE = "accountUserAge";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_user
     *
     * @mbg.generated Mon Apr 29 20:19:51 CST 2019
     */
    public static final String ACCOUNT_USER_SEX = "accountUserSex";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_user
     *
     * @mbg.generated Mon Apr 29 20:19:51 CST 2019
     */
    public static final String ACCOUNT_USER_MOBILE_PHONE = "accountUserMobilePhone";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_user
     *
     * @mbg.generated Mon Apr 29 20:19:51 CST 2019
     */
    public static final String ACCOUNT_USER_FAMILY_PHONE = "accountUserFamilyPhone";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_user
     *
     * @mbg.generated Mon Apr 29 20:19:51 CST 2019
     */
    public static final String ACCOUNT_USER_FAMILY_ADDR = "accountUserFamilyAddr";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_user
     *
     * @mbg.generated Mon Apr 29 20:19:51 CST 2019
     */
    public static final String ACCOUNT_USER_PASSWORD = "accountUserPassword";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_user
     *
     * @mbg.generated Mon Apr 29 20:19:51 CST 2019
     */
    public static final String ACCOUNT_USER_TOTAL_TIMES = "accountUserTotalTimes";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_user
     *
     * @mbg.generated Mon Apr 29 20:19:51 CST 2019
     */
    public static final String ACCOUNT_USER_FAIL_TIMES = "accountUserFailTimes";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_user
     *
     * @mbg.generated Mon Apr 29 20:19:51 CST 2019
     */
    public static final String ACCOUNT_USER_CRTIME = "accountUserCrtime";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_user
     *
     * @mbg.generated Mon Apr 29 20:19:51 CST 2019
     */
    public static final String ACCOUNT_USER_LAST_MODFTIME = "accountUserLastModftime";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_user
     *
     * @mbg.generated Mon Apr 29 20:19:51 CST 2019
     */
    public static final String ACCOUNT_USER_LAST_SIGNINTIME = "accountUserLastSignintime";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_user
     *
     * @mbg.generated Mon Apr 29 20:19:51 CST 2019
     */
    public static final String ACCOUNT_USER_EMAIL_ADDR = "accountUserEmailAddr";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_user
     *
     * @mbg.generated Mon Apr 29 20:19:51 CST 2019
     */
    public static final String TABLE_NAME = "t_accountmanger_user";
}