package com.ziania.accountmanager.domain;

public class TAccountmangerAccount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_account
     *
     * @mbg.generated Tue May 21 20:02:51 CST 2019
     */
    public static final String PK_ACCOUNT_ID = "accountId";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_account
     *
     * @mbg.generated Tue May 21 20:02:51 CST 2019
     */
    public static final String ACCOUNT_ID = "accountId";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_account
     *
     * @mbg.generated Tue May 21 20:02:51 CST 2019
     */
    public static final String ACCOUNT_NAME = "accountName";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_account
     *
     * @mbg.generated Tue May 21 20:02:51 CST 2019
     */
    public static final String ACCOUNT_PASSWORD = "accountPassword";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_account
     *
     * @mbg.generated Tue May 21 20:02:51 CST 2019
     */
    public static final String ACCOUNT_ADDRESS = "accountAddress";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_account
     *
     * @mbg.generated Tue May 21 20:02:51 CST 2019
     */
    public static final String ACCOUNT_USED_TYPE = "accountUsedType";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_account
     *
     * @mbg.generated Tue May 21 20:02:51 CST 2019
     */
    public static final String ACCOUNT_STARTIME = "accountStartime";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_account
     *
     * @mbg.generated Tue May 21 20:02:51 CST 2019
     */
    public static final String ACCOUNT_ENDTIME = "accountEndtime";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_account
     *
     * @mbg.generated Tue May 21 20:02:51 CST 2019
     */
    public static final String ACCOUNT_VALID_FLAG = "accountValidFlag";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_account
     *
     * @mbg.generated Tue May 21 20:02:51 CST 2019
     */
    public static final String ACCOUNT_OWNER = "accountOwner";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_account
     *
     * @mbg.generated Tue May 21 20:02:51 CST 2019
     */
    public static final String ACCOUNT_CRTIME = "accountCrtime";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_account
     *
     * @mbg.generated Tue May 21 20:02:51 CST 2019
     */
    public static final String ACCOUNT_MODFIME = "accountModfime";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_account
     *
     * @mbg.generated Tue May 21 20:02:51 CST 2019
     */
    public static final String ACCOUNT_RMK = "accountRmk";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_account
     *
     * @mbg.generated Tue May 21 20:02:51 CST 2019
     */
    public static final String TABLE_NAME = "t_accountmanger_account";
}