package com.ziania.accountmanager.domain;

public class TAccountmangerDatabase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_database
     *
     * @mbg.generated Fri May 17 17:57:30 CST 2019
     */
    public static final String PK_DATA_BASE_ID = "dataBaseId";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_database
     *
     * @mbg.generated Fri May 17 17:57:30 CST 2019
     */
    public static final String DATA_BASE_ID = "dataBaseId";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_database
     *
     * @mbg.generated Fri May 17 17:57:30 CST 2019
     */
    public static final String DATA_BASE_VERSION = "dataBaseVersion";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_database
     *
     * @mbg.generated Fri May 17 17:57:30 CST 2019
     */
    public static final String DATA_BASE_TYPE = "dataBaseType";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_database
     *
     * @mbg.generated Fri May 17 17:57:30 CST 2019
     */
    public static final String DATA_BASE_IP = "dataBaseIp";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_database
     *
     * @mbg.generated Fri May 17 17:57:30 CST 2019
     */
    public static final String DATA_BASE_PORT = "dataBasePort";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_database
     *
     * @mbg.generated Fri May 17 17:57:30 CST 2019
     */
    public static final String DATA_BASE_USER = "dataBaseUser";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_database
     *
     * @mbg.generated Fri May 17 17:57:30 CST 2019
     */
    public static final String DATA_BASE_PWD = "dataBasePwd";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_database
     *
     * @mbg.generated Fri May 17 17:57:30 CST 2019
     */
    public static final String VALID_FLAG = "validFlag";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_database
     *
     * @mbg.generated Fri May 17 17:57:30 CST 2019
     */
    public static final String CREATE_TIME = "createTime";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_database
     *
     * @mbg.generated Fri May 17 17:57:30 CST 2019
     */
    public static final String MODIFY_TIME = "modifyTime";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_database
     *
     * @mbg.generated Fri May 17 17:57:30 CST 2019
     */
    public static final String OPERATE_STAFF = "operateStaff";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_database
     *
     * @mbg.generated Fri May 17 17:57:30 CST 2019
     */
    public static final String RMK = "rmk";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_database
     *
     * @mbg.generated Fri May 17 17:57:30 CST 2019
     */
    public static final String TABLE_NAME = "t_accountmanger_database";
}