package com.ziania.accountmanager.domain;

public class TAccountmangerMenus {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_menus
     *
     * @mbg.generated Tue May 28 17:33:14 CST 2019
     */
    public static final String PK_MENU_ID = "menuId";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_menus
     *
     * @mbg.generated Tue May 28 17:33:14 CST 2019
     */
    public static final String MENU_ID = "menuId";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_menus
     *
     * @mbg.generated Tue May 28 17:33:14 CST 2019
     */
    public static final String MENU_NAME = "menuName";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_menus
     *
     * @mbg.generated Tue May 28 17:33:14 CST 2019
     */
    public static final String MENU_URL = "menuUrl";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_menus
     *
     * @mbg.generated Tue May 28 17:33:14 CST 2019
     */
    public static final String SUPER_MENU_ID = "superMenuId";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_menus
     *
     * @mbg.generated Tue May 28 17:33:14 CST 2019
     */
    public static final String LEAF_FLAG = "leafFlag";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_menus
     *
     * @mbg.generated Tue May 28 17:33:14 CST 2019
     */
    public static final String MENU_OWNER = "menuOwner";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_menus
     *
     * @mbg.generated Tue May 28 17:33:14 CST 2019
     */
    public static final String VALID_FLAG = "validFlag";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_menus
     *
     * @mbg.generated Tue May 28 17:33:14 CST 2019
     */
    public static final String CREATE_TIME = "createTime";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_menus
     *
     * @mbg.generated Tue May 28 17:33:14 CST 2019
     */
    public static final String MODIFY_TIME = "modifyTime";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_menus
     *
     * @mbg.generated Tue May 28 17:33:14 CST 2019
     */
    public static final String OPERATE_STAFF = "operateStaff";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_menus
     *
     * @mbg.generated Tue May 28 17:33:14 CST 2019
     */
    public static final String RMK = "rmk";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_menus
     *
     * @mbg.generated Tue May 28 17:33:14 CST 2019
     */
    public static final String TABLE_NAME = "t_accountmanger_menus";
}