package com.ziania.accountmanager.domain;

public class TAccountmangerCode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_code
     *
     * @mbg.generated Tue May 14 11:00:16 CST 2019
     */
    public static final String CODE_ID = "codeId";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_code
     *
     * @mbg.generated Tue May 14 11:00:16 CST 2019
     */
    public static final String CODE_TYPE_CD = "codeTypeCd";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_code
     *
     * @mbg.generated Tue May 14 11:00:16 CST 2019
     */
    public static final String CODE_TYPE_NAME = "codeTypeName";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_code
     *
     * @mbg.generated Tue May 14 11:00:16 CST 2019
     */
    public static final String CODE_FULL_NAME = "codeFullName";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_code
     *
     * @mbg.generated Tue May 14 11:00:16 CST 2019
     */
    public static final String CODE_NAME = "codeName";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_code
     *
     * @mbg.generated Tue May 14 11:00:16 CST 2019
     */
    public static final String LEAF_NODE_FLAG = "leafNodeFlag";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_code
     *
     * @mbg.generated Tue May 14 11:00:16 CST 2019
     */
    public static final String SUPER_BIZ_CODE = "superBizCode";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_code
     *
     * @mbg.generated Tue May 14 11:00:16 CST 2019
     */
    public static final String BIZ_CODE = "bizCode";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_code
     *
     * @mbg.generated Tue May 14 11:00:16 CST 2019
     */
    public static final String ARGE_SEQNO = "argeSeqno";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_code
     *
     * @mbg.generated Tue May 14 11:00:16 CST 2019
     */
    public static final String VALID_FLAG = "validFlag";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_code
     *
     * @mbg.generated Tue May 14 11:00:16 CST 2019
     */
    public static final String CREATE_TIME = "createTime";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_code
     *
     * @mbg.generated Tue May 14 11:00:16 CST 2019
     */
    public static final String MODIFY_TIME = "modifyTime";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_code
     *
     * @mbg.generated Tue May 14 11:00:16 CST 2019
     */
    public static final String OPERATE_STAFF = "operateStaff";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_code
     *
     * @mbg.generated Tue May 14 11:00:16 CST 2019
     */
    public static final String RMK = "rmk";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_accountmanger_code
     *
     * @mbg.generated Tue May 14 11:00:16 CST 2019
     */
    public static final String TABLE_NAME = "t_accountmanger_code";
}