package com.ziania.accountmanager.dao.interfaces;

import com.ziania.accountmanager.exception.CommonException;

import java.util.Map;

public interface ITAccountmangerUserService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_accountmanger_user
     *
     * @mbg.generated Mon Apr 29 20:19:51 CST 2019
     */
    Map countByCond(Map params) throws CommonException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_accountmanger_user
     *
     * @mbg.generated Mon Apr 29 20:19:51 CST 2019
     */
    Map selectByCond(Map params) throws CommonException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_accountmanger_user
     *
     * @mbg.generated Mon Apr 29 20:19:51 CST 2019
     */
    Map selectByPrimaryKey(Map params) throws CommonException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_accountmanger_user
     *
     * @mbg.generated Mon Apr 29 20:19:51 CST 2019
     */
    Map deleteByCond(Map params) throws CommonException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_accountmanger_user
     *
     * @mbg.generated Mon Apr 29 20:19:51 CST 2019
     */
    Map deleteByPrimaryKey(Map params) throws CommonException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_accountmanger_user
     *
     * @mbg.generated Mon Apr 29 20:19:51 CST 2019
     */
    Map updateByPrimaryKey(Map params) throws CommonException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_accountmanger_user
     *
     * @mbg.generated Mon Apr 29 20:19:51 CST 2019
     */
    Map insertSelective(Map params) throws CommonException;
}