package com.ziania.accountmanager.dao.interfaces;

import com.ziania.accountmanager.exception.CommonException;

import java.util.Map;

public interface ITAccountmangerCodeService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_accountmanger_code
     *
     * @mbg.generated Tue May 14 11:00:16 CST 2019
     */
    Map countByCond(Map params) throws CommonException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_accountmanger_code
     *
     * @mbg.generated Tue May 14 11:00:16 CST 2019
     */
    Map selectByCond(Map params) throws CommonException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_accountmanger_code
     *
     * @mbg.generated Tue May 14 11:00:16 CST 2019
     */
    Map selectByPrimaryKey(Map params) throws CommonException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_accountmanger_code
     *
     * @mbg.generated Tue May 14 11:00:16 CST 2019
     */
    Map deleteByCond(Map params) throws CommonException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_accountmanger_code
     *
     * @mbg.generated Tue May 14 11:00:16 CST 2019
     */
    Map deleteByPrimaryKey(Map params) throws CommonException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_accountmanger_code
     *
     * @mbg.generated Tue May 14 11:00:16 CST 2019
     */
    Map updateByPrimaryKey(Map params) throws CommonException;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_accountmanger_code
     *
     * @mbg.generated Tue May 14 11:00:16 CST 2019
     */
    Map insertSelective(Map params) throws CommonException;
}