package com.ziania.accountmanager.dao.impls;

import com.ziania.accountmanager.dao.interfaces.ITAccountmangerUserService;
import com.ziania.accountmanager.domain.TAccountmangerUser;
import com.ziania.accountmanager.exception.CommonException;
import com.ziania.accountmanager.service.BaseServiceImpl;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.apache.commons.collections.MapUtils;
import org.springframework.stereotype.Repository;

@Repository("accountmangerUserServiceImpl")
public class TAccountmangerUserServiceImpl extends BaseServiceImpl implements ITAccountmangerUserService {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_accountmanger_user
     *
     * @mbg.generated Mon Apr 29 20:19:51 CST 2019
     */
    public Map countByCond(Map params) throws CommonException {
        Map<String, Object> returnMap = new HashMap<>();
        if (MapUtils.isNotEmpty(params)) {
            params.put(TAccountmangerUser.TABLE_NAME, TAccountmangerUser.TABLE_NAME);
            int total = getBaseDao().queryCount("com.ziania.accountmanager.dao.TAccountmangerUserMapper.countByCond", params);
            returnMap.put("total", total);
        } else {
            returnMap.put("total", 0);
        }
        return returnMap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_accountmanger_user
     *
     * @mbg.generated Mon Apr 29 20:19:51 CST 2019
     */
    public Map selectByCond(Map params) throws CommonException {
        Map<String, Object> returnMap = new HashMap<>();
        params.put(TAccountmangerUser.TABLE_NAME, TAccountmangerUser.TABLE_NAME);
        Map<String, Object> countMap = this.countByCond(params);
        if (MapUtils.getInteger(countMap, "total") > 0) {
            List<Map<String, Object>> queryList = getBaseDao().selectByCond("com.ziania.accountmanager.dao.TAccountmangerUserMapper.selectByCond", params);
            returnMap.put("total", MapUtils.getInteger(countMap, "total"));
            returnMap.put("beans", queryList);
        }
        return returnMap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_accountmanger_user
     *
     * @mbg.generated Mon Apr 29 20:19:51 CST 2019
     */
    public Map selectByPrimaryKey(Map params) throws CommonException {
        Map<String, Object> returnMap = new HashMap<>();
        params.put(TAccountmangerUser.TABLE_NAME, TAccountmangerUser.TABLE_NAME);
        Map<String, Object> objectMap = (Map<String, Object>)getBaseDao().selectByPrimaryKey("com.ziania.accountmanager.dao.TAccountmangerUserMapper.selectByPrimaryKey", params);
        returnMap.put("bean", objectMap);
        return returnMap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_accountmanger_user
     *
     * @mbg.generated Mon Apr 29 20:19:51 CST 2019
     */
    public Map deleteByCond(Map params) throws CommonException {
        Map<String, Object> returnMap = new HashMap<>();
        params.put(TAccountmangerUser.TABLE_NAME, TAccountmangerUser.TABLE_NAME);
        int deleteCount = getBaseDao().deleteByCond("com.ziania.accountmanager.dao.TAccountmangerUserMapper.deleteByCond", params);
        returnMap.put("deleteCount", deleteCount);
        return returnMap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_accountmanger_user
     *
     * @mbg.generated Mon Apr 29 20:19:51 CST 2019
     */
    public Map deleteByPrimaryKey(Map params) throws CommonException {
        Map<String, Object> returnMap = new HashMap<>();
        params.put(TAccountmangerUser.TABLE_NAME, TAccountmangerUser.TABLE_NAME);
        int deleteCount = getBaseDao().deleteByPrimaryKey("com.ziania.accountmanager.dao.TAccountmangerUserMapper.deleteByPrimaryKey", params);
        returnMap.put("deleteCount", deleteCount);
        return returnMap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_accountmanger_user
     *
     * @mbg.generated Mon Apr 29 20:19:51 CST 2019
     */
    public Map updateByPrimaryKey(Map params) throws CommonException {
        Map<String, Object> returnMap = new HashMap<>();
        params.put(TAccountmangerUser.TABLE_NAME, TAccountmangerUser.TABLE_NAME);
        int updateCount = getBaseDao().updateByPrimaryKey("com.ziania.accountmanager.dao.TAccountmangerUserMapper.updateByPrimaryKey", params);
        returnMap.put("updateCount", updateCount);
        return returnMap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_accountmanger_user
     *
     * @mbg.generated Mon Apr 29 20:19:51 CST 2019
     */
    public Map insertSelective(Map params) throws CommonException {
        Map<String, Object> returnMap = new HashMap<>();
        params.put(TAccountmangerUser.TABLE_NAME, TAccountmangerUser.TABLE_NAME);
        int insertCount = getBaseDao().insertSelective("com.ziania.accountmanager.dao.TAccountmangerUserMapper.insertSelective", params);
        returnMap.put("insertCount", insertCount);
        return returnMap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_accountmanger_user
     *
     * @mbg.generated Mon Apr 29 20:19:51 CST 2019
     */
    public Map insertBatch(Map params) throws CommonException {
        Map<String, Object> returnMap = new HashMap<>();
        params.put(TAccountmangerUser.TABLE_NAME, TAccountmangerUser.TABLE_NAME);
        int insertCount = getBaseDao().insertSelective("com.ziania.accountmanager.dao.TAccountmangerUserMapper.insertBatch", params);
        returnMap.put("insertCount", insertCount);
        return returnMap;
    }
}